# Generated by Django 5.0 on 2023-12-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeaFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Наименование')),
                ('proiz', models.CharField(max_length=75, verbose_name='Производиьтель')),
                ('price', models.CharField(max_length=75, verbose_name='Цена')),
                ('descr', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
