# Generated by Django 5.0 on 2023-12-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_seafood_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seafood',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
