# Generated by Django 5.0 on 2023-12-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seafood_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seafood',
            old_name='image',
            new_name='photo',
        ),
    ]
